export { default as ToyIconAdd } from './svg/toy-add.svg'
export { default as ToyIconAlbums } from './svg/toy-albums.svg'
export { default as ToyIconFavorite } from './svg/toy-favorite.svg'
export { default as ToyIconIosRemove } from './svg/toy-ios-remove.svg'
export { default as ToyIconLoading } from './svg/toy-loading.svg'
